#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v18
# autospec commit: eaa4f711da30
#
Name     : libopusenc
Version  : 0.2.1
Release  : 1
URL      : https://ftp.osuosl.org/pub/xiph/releases/opus/libopusenc-0.2.1.tar.gz
Source0  : https://ftp.osuosl.org/pub/xiph/releases/opus/libopusenc-0.2.1.tar.gz
Summary  : High-level Opus encoding library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libopusenc-lib = %{version}-%{release}
Requires: libopusenc-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : pkgconfig(opus)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Libopusenc
[![Travis Build Status](https://travis-ci.org/xiph/libopusenc.svg?branch=master)](https://travis-ci.org/xiph/libopusenc)

%package dev
Summary: dev components for the libopusenc package.
Group: Development
Requires: libopusenc-lib = %{version}-%{release}
Provides: libopusenc-devel = %{version}-%{release}
Requires: libopusenc = %{version}-%{release}

%description dev
dev components for the libopusenc package.


%package doc
Summary: doc components for the libopusenc package.
Group: Documentation

%description doc
doc components for the libopusenc package.


%package lib
Summary: lib components for the libopusenc package.
Group: Libraries
Requires: libopusenc-license = %{version}-%{release}

%description lib
lib components for the libopusenc package.


%package license
Summary: license components for the libopusenc package.
Group: Default

%description license
license components for the libopusenc package.


%prep
%setup -q -n libopusenc-0.2.1
cd %{_builddir}/libopusenc-0.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724791192
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1724791192
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libopusenc
cp %{_builddir}/libopusenc-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libopusenc/76288bf672ef944e804a208117d80856f9a7d38d || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/opus/opusenc.h
/usr/lib64/libopusenc.so
/usr/lib64/pkgconfig/libopusenc.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libopusenc/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopusenc.so.0
/usr/lib64/libopusenc.so.0.4.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libopusenc/76288bf672ef944e804a208117d80856f9a7d38d
